usePlasticity: False  # Set to True to enable plasticity, or False to disable it
timeThresholdLow: 10  # Define the lower time threshold
timeThresholdHigh: 11  # Define the higher time threshold
# initialSpeed: 0.2 #Defing starting linear velocity in m/s
# linearRange: 50000 #Defining how far forward robot goes before rotating
# angularRange: 1000 #Defining the rotating of the robot 
# initialAcc: 10